version: "3.9"
services:
  micro-db:
    container_name: micro-db-${ENVIRONMENT}-container
    image: postgres:latest
    volumes:
      - ./micro-api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}-db-${ENVIRONMENT}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - micro
    restart: always
  micro-api:
    container_name: micro-api-${ENVIRONMENT}-container
    build: ./micro-api
    command: bash -c "rm -f /micro-api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - micro-db
    env_file:
      - .env
    volumes:
      - ./micro-api:/micro-api
    networks:
      - micro
    restart: always
networks:
  micro:
    name: micro
    driver: bridge
